# Generated by Django 3.0.6 on 2020-09-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gues_Emai',
            new_name='Guest_Email',
        ),
    ]
