# Generated by Django 3.1.3 on 2020-11-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ending_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ends', to='catalogue.servicestop')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='catalogue.service')),
                ('starting_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starts', to='catalogue.servicestop')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_prior', models.IntegerField()),
                ('effective_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_prices', to='price_availability.price')),
            ],
        ),
        migrations.CreateModel(
            name='CancellationPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_prior', models.IntegerField()),
                ('charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_prices', to='price_availability.price')),
            ],
        ),
    ]
