# Generated by Django 3.1.3 on 2020-11-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='MiddleStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_distance', models.DecimalField(decimal_places=1, max_digits=6)),
                ('destination_distance', models.DecimalField(decimal_places=1, max_digits=6)),
                ('facility', models.ManyToManyField(to='catalogue.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('bus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalogue.bustype')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_services', to='catalogue.route')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='catalogue.city')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_arrival', models.TimeField()),
                ('scheduled_departure', models.TimeField()),
                ('middle_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_stop_services', to='catalogue.middlestop')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_stops', to='catalogue.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=12)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_days', to='catalogue.service')),
            ],
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.PositiveSmallIntegerField()),
                ('occupancy', models.PositiveSmallIntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='catalogue.bus')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating', to='catalogue.seattype')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='catalogue.stop'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='catalogue.stop'),
        ),
        migrations.AddField(
            model_name='middlestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_stops', to='catalogue.route'),
        ),
        migrations.AddField(
            model_name='middlestop',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalogue.stop'),
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busses', to='catalogue.bustype'),
        ),
        migrations.AddField(
            model_name='bus',
            name='facility',
            field=models.ManyToManyField(to='catalogue.Facility'),
        ),
    ]
